import { Box, Link } from "@mui/material";
import Head from "next/head";

export default function Header() {
  return (
    <Box sx={{ textAlign: 'center' }}>
      <Head>
        <title>Box Functions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/"><h1>Box Functions</h1></Link>
    </Box>
  )
}